---
title: "The semantics of Hmong indefinites"
author: "Quartz Colvin"
institute: "Rutgers University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["rutgers", "rutgers-fonts"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# Introduction

- This project argues for a choice functional analysis of the indefinite article in White Hmong.

- Our discussion includes the indefinite article *ib* and two common classifiers (*tus* and *cov*).

---

## Research questions

1. What are the individual meanings of *ib*, *tus*, and *cov*?

2. How does the indefinite article *ib* combine with with *tus* and *cov* classifier phrases?

---

## Roadmap 

**FILL IN???**

---

# Data

## Demographics

- All of my data and discussion are based on elicitation on Zoom with Mai-Ying Xiong and in person with Keng
Xiong, two White Hmong speakers who were raised in Wisconsin. 

- Keng was born in Wisconsin and Ying immigrated to the US at age 4.

---

## Definites (Bare classifier phrases)

**FILL IN???**

---

## Indefinites 

**FILL IN???**

--

**ib aub is bad example???**


---

# Proposal 

## Definites

**classifier denotations???**

**what do these mean???**

**takes type e kind and returns a predicate of type e,t???**

---

## Definites 

**iota definition???**

**what's it do???**

**show mini definite DP trees???**

---

## Indefinites

**ib denotation???**

**what's this mean???**

**what is the type???**

---

## Contexts 

**show tus aub and ib tus aub???**

**how are the referents determined in both sentences???**

---

## Contexts 

**show cov aub and ib cov aub???**

--

**show antipresup options???**

--

**how are the referents determined???**

---

### Antipresupposition

**FILL IN???**

---

# Conclusion 

**FILL IN???**

---

## References 

**FILL IN???**

Slides created via the R package [**xaringan**](https://github.com/yihui/xaringan).

The chakra comes from [remark.js](https://remarkjs.com), [**knitr**](https://yihui.org/knitr/), and [R Markdown](https://rmarkdown.rstudio.com).

---

class: center, middle

# Thanks!

# Cov aub! 

**FILL IN???**
